repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: '.bumpversion.cfg'
      - id: trailing-whitespace
        exclude: '.bumpversion.cfg'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        additional_dependencies:
          - "sqlalchemy[mypy]==2.0.12"
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
